version: '3'

services:
  # client:
  #   container_name: client
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   command: npm run preview
  #   ports:
  #     - '3000:${CLIENT_PORT:-3000}'

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=0
      - PYTHONPATH=/app/server
      - ENVIRONMENT=production
    restart: always
    command:
      - sh
      - -c
      - 'alembic upgrade head && uvicorn server.src.main:app --host 0.0.0.0 --port ${SERVER_PORT:-8000}'
    ports:
      - '8000:${SERVER_PORT:-8000}'
    volumes:
      - ./server:/app/server
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file: .env
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   depends_on:
  #     - client
  #     - server
  #   environment:
  #     CLIENT_PORT: ${CLIENT_PORT:-3000}
  #     SERVER_PORT: ${SERVER_PORT:-8000}

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
