apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  labels:
    app: nextcloud
data:
  NEXTCLOUD_UPDATE: "1"
  ALLOW_EMPTY_PASSWORD: "yes"
  NEXTCLOUD_TRUSTED_DOMAINS: "127.0.0.1"
